### ISSUE TITLE
[1.20.1, 1.20.4] v1.0.0 and v1.0.1 Require Java 21

### ISSUE THREAD

**Issue by mr-yours-truly** [pnk2u/Nemos-More-Ladder-Variants#1]
The default Java version for Minecraft 1.20.1 and 1.20.4 is Java 17, when the mod calls for use of Java 21. When loading the mod on either version with only it's own dependencies, the game crashes with the following error for both v1.0.0 and v1.0.1:
![Screenshot_nmlv](https://github.com/user-attachments/assets/cd9d6145-760c-4d41-ab52-eed2a04614ce)
Tested on the Steam Deck OLED 512GB and Prism launcher v8.4 (Flatpak).

**Comment by pnk2u** [comment]
Thanks for reporting. I'm sorry about the many oversights regarding this. It is fixed in the just uploaded version 1.0.2.
